compatibility_date = "2024-10-12"
compatibility_flags = ["nodejs_compat"]
main = "src/index.ts"
name = "formsubmit-portfolio-api"

[vars]
Recipient = "shakibhasan.me09@gmail.com"

send_email = [
  {type = "send_email", name = "EMAIL", destination_address = "shakibhasan.me09@gmail.com"},
]

[observability]
enabled = true
head_sampling_rate = 1
